// Deterministic data layer behind the Telegram agent's CRUD tools.
//
// Two rules hold everywhere in this file:
//   1. Every query is scoped by user_id. Row ids are supplied by the LLM, so an
//      id alone is never enough to touch a row — it must also belong to the
//      caller. A wrong or hallucinated id yields "not found", never someone
//      else's data.
//   2. No SQL is ever generated by the model. It picks a tool and arguments;
//      the queries live here.
//
// Mutations are two-phase: previewMutation() validates and renders what would
// change, applyMutation() performs it after the user taps Confirm.
import { supabase } from '../supabase.js';
import { formatAmount, remindPerson } from './reminders.js';
import { getUserContext, closestName } from './telegramLedger.js';

const PAYMENT_MODES = ['upi', 'cash', 'card', 'bank_transfer', 'other'];
const MAX_LIMIT = 100;

function norm(s = '') {
  return String(s).trim().toLowerCase();
}

// Previews are interpolated into Telegram HTML messages, so anything
// user-authored (names, notes) has to be escaped here.
function esc(s = '') {
  return String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function badRequest(message) {
  const e = new Error(message);
  e.code = 'TOOL_BAD_REQUEST';
  return e;
}

function clampLimit(n, fallback = 20) {
  const v = Number(n);
  if (!Number.isFinite(v) || v <= 0) return fallback;
  return Math.min(Math.floor(v), MAX_LIMIT);
}

function isDate(s) {
  return typeof s === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(s);
}

function isMonth(s) {
  return typeof s === 'string' && /^\d{4}-\d{2}$/.test(s);
}

// ── person resolution ──────────────────────────────────────────────────
// Exact (case-insensitive) first, then substring. Several substring hits is
// ambiguous rather than a guess — picking the wrong friend silently writes to
// the wrong ledger.
export async function resolvePerson(userId, name) {
  if (!name || !String(name).trim()) throw badRequest('A person name is required.');
  const { data: people } = await supabase
    .from('people')
    .select('id, name, description, email, phone, whatsapp, reminders_on')
    .eq('user_id', userId);

  const roster = people || [];
  const want = norm(name);

  const exact = roster.filter((p) => norm(p.name) === want);
  if (exact.length === 1) return { found: true, person: exact[0] };

  const partial = roster.filter((p) => norm(p.name).includes(want) || want.includes(norm(p.name)));
  if (partial.length === 1) return { found: true, person: partial[0] };
  if (partial.length > 1) {
    return { found: false, ambiguous: true, candidates: partial.map((p) => p.name) };
  }

  const near = closestName(name, roster.map((p) => p.name));
  if (near) return { found: true, person: roster.find((p) => p.name === near) };

  return { found: false, ambiguous: false, candidates: roster.map((p) => p.name) };
}

// ── reads ──────────────────────────────────────────────────────────────

// Contacts with their current balance and contact details. Ids are included so
// the model can follow up with an update or delete.
export async function listPeople(userId) {
  const [{ data: people }, { data: balances }, { currency }] = await Promise.all([
    supabase
      .from('people')
      .select('id, name, description, email, phone, whatsapp, reminders_on')
      .eq('user_id', userId)
      .order('name'),
    supabase.from('person_balances').select('person_id, balance').eq('user_id', userId),
    getUserContext(userId),
  ]);

  const balanceById = new Map((balances || []).map((b) => [b.person_id, Number(b.balance)]));
  const list = (people || []).map((p) => ({
    id: p.id,
    name: p.name,
    balance: balanceById.get(p.id) ?? 0,
    formatted: formatAmount(balanceById.get(p.id) ?? 0, currency),
    description: p.description || null,
    email: p.email || null,
    phone: p.phone || null,
    whatsapp: p.whatsapp || null,
    reminders_on: p.reminders_on,
  }));
  list.sort((a, b) => b.balance - a.balance);

  const total = list.reduce((sum, p) => sum + p.balance, 0);
  return {
    currency,
    total_people: list.length,
    total_outstanding: total,
    total_outstanding_formatted: formatAmount(total, currency),
    people: list,
  };
}

export async function listCategories(userId) {
  const { data } = await supabase
    .from('expense_categories')
    .select('id, name, is_system')
    .or(`is_system.eq.true,user_id.eq.${userId}`)
    .order('name');
  return { categories: (data || []).map((c) => ({ id: c.id, name: c.name, custom: !c.is_system })) };
}

async function resolveCategory(userId, name) {
  if (!name) return null;
  const { data: cats } = await supabase
    .from('expense_categories')
    .select('id, name')
    .or(`is_system.eq.true,user_id.eq.${userId}`);
  const want = norm(name);
  const list = cats || [];
  return (
    list.find((c) => norm(c.name) === want) ||
    list.find((c) => norm(c.name).includes(want) || want.includes(norm(c.name))) ||
    null
  );
}

// The workhorse read. One tool covers "show everything", "what did I spend on
// food in July", "find the pizza entry" and "Lakshya's full history", because
// they are the same query with different filters.
export async function findExpenses(userId, filters = {}) {
  const {
    scope = 'both',
    person,
    category,
    query,
    from,
    to,
    min_amount,
    max_amount,
    limit,
  } = filters;

  if (!['both', 'friend', 'personal'].includes(scope)) {
    throw badRequest(`scope must be "both", "friend" or "personal" (got "${scope}").`);
  }
  for (const [label, v] of [['from', from], ['to', to]]) {
    if (v != null && !isDate(v)) throw badRequest(`${label} must be a YYYY-MM-DD date.`);
  }

  const { currency } = await getUserContext(userId);
  const cap = clampLimit(limit);
  const result = { currency, scope };

  let personRow = null;
  if (person) {
    const r = await resolvePerson(userId, person);
    if (!r.found) {
      return {
        ...result,
        found: false,
        message: r.ambiguous
          ? `More than one contact matches "${person}": ${r.candidates.join(', ')}. Ask which one.`
          : `No contact named "${person}". Known contacts: ${r.candidates.join(', ') || 'none yet'}.`,
      };
    }
    personRow = r.person;
  }

  const wantFriend = scope !== 'personal';
  const wantPersonal = scope !== 'friend' && !personRow; // friend filter implies the friend ledger

  if (wantFriend) {
    let q = supabase
      .from('expenses')
      .select('id, person_id, amount, note, incurred_on')
      .eq('user_id', userId)
      .order('incurred_on', { ascending: false })
      .order('created_at', { ascending: false })
      .limit(cap);

    if (personRow) q = q.eq('person_id', personRow.id);
    if (query) q = q.ilike('note', `%${query}%`);
    if (from) q = q.gte('incurred_on', from);
    if (to) q = q.lte('incurred_on', to);

    const { data, error } = await q;
    if (error) throw new Error(`Could not read the friend ledger: ${error.message}`);

    // Names for the rows we got back, so the model can talk about them.
    const nameById = new Map();
    if (personRow) {
      nameById.set(personRow.id, personRow.name);
    } else {
      const { data: people } = await supabase
        .from('people').select('id, name').eq('user_id', userId);
      for (const p of people || []) nameById.set(p.id, p.name);
    }

    const rows = (data || [])
      .map((e) => ({
        id: e.id,
        person: nameById.get(e.person_id) || 'Unknown',
        amount: Number(e.amount),
        formatted: formatAmount(Number(e.amount), currency),
        note: e.note || null,
        date: e.incurred_on,
      }))
      .filter((r) => withinAmount(Math.abs(r.amount), min_amount, max_amount));

    result.friend_expenses = rows;
    result.friend_total = rows.reduce((s, r) => s + r.amount, 0);
    result.friend_total_formatted = formatAmount(result.friend_total, currency);
    if (personRow) {
      const { data: bal } = await supabase
        .from('person_balances').select('balance').eq('person_id', personRow.id).maybeSingle();
      result.person = personRow.name;
      result.person_balance = Number(bal?.balance ?? 0);
      result.person_balance_formatted = formatAmount(Number(bal?.balance ?? 0), currency);
    }
  }

  if (wantPersonal) {
    let catRow = null;
    if (category) {
      catRow = await resolveCategory(userId, category);
      if (!catRow) {
        const { categories } = await listCategories(userId);
        return {
          ...result,
          found: false,
          message: `No category matching "${category}". Available: ${categories.map((c) => c.name).join(', ')}.`,
        };
      }
    }

    let q = supabase
      .from('personal_expenses')
      .select('id, amount, note, payment_mode, incurred_on, category_id')
      .eq('user_id', userId)
      .order('incurred_on', { ascending: false })
      .order('created_at', { ascending: false })
      .limit(cap);

    if (catRow) q = q.eq('category_id', catRow.id);
    if (query) q = q.ilike('note', `%${query}%`);
    if (from) q = q.gte('incurred_on', from);
    if (to) q = q.lte('incurred_on', to);

    const { data, error } = await q;
    if (error) throw new Error(`Could not read personal expenses: ${error.message}`);

    const { categories } = await listCategories(userId);
    const catById = new Map(categories.map((c) => [c.id, c.name]));

    const rows = (data || [])
      .map((e) => ({
        id: e.id,
        amount: Number(e.amount),
        formatted: formatAmount(Number(e.amount), currency),
        note: e.note || null,
        category: catById.get(e.category_id) || 'Uncategorised',
        payment_mode: e.payment_mode,
        date: e.incurred_on,
      }))
      .filter((r) => withinAmount(r.amount, min_amount, max_amount));

    result.personal_expenses = rows;
    result.personal_total = rows.reduce((s, r) => s + r.amount, 0);
    result.personal_total_formatted = formatAmount(result.personal_total, currency);
  }

  result.found = true;
  result.note_to_assistant =
    `Up to ${cap} rows per section, newest first. Use the "id" of a row when editing or deleting it.`;
  return result;
}

function withinAmount(value, min, max) {
  if (min != null && Number.isFinite(Number(min)) && value < Number(min)) return false;
  if (max != null && Number.isFinite(Number(max)) && value > Number(max)) return false;
  return true;
}

// Aggregates. `month` is YYYY-MM; omit for all-time where it makes sense.
export async function getSummary(userId, { kind = 'everything', month } = {}) {
  if (month != null && !isMonth(month)) throw badRequest('month must be YYYY-MM.');
  const valid = ['balances', 'spending', 'budget', 'everything'];
  if (!valid.includes(kind)) throw badRequest(`kind must be one of ${valid.join(', ')}.`);

  const { currency } = await getUserContext(userId);
  const out = { currency, month: month || null };

  if (kind === 'balances' || kind === 'everything') {
    const { people, total_outstanding, total_outstanding_formatted } = await listPeople(userId);
    out.balances = {
      total_outstanding,
      total_outstanding_formatted,
      people: people.map(({ name, balance, formatted }) => ({ name, balance, formatted })),
    };
  }

  if (kind === 'spending' || kind === 'budget' || kind === 'everything') {
    const range = month ? monthRange(month) : null;
    let q = supabase
      .from('personal_expenses')
      .select('amount, incurred_on, category_id')
      .eq('user_id', userId);
    if (range) q = q.gte('incurred_on', range.start).lte('incurred_on', range.end);

    const { data } = await q;
    const rows = data || [];
    const { categories } = await listCategories(userId);
    const catById = new Map(categories.map((c) => [c.id, c.name]));

    const byCategory = new Map();
    const byMonth = new Map();
    let total = 0;
    for (const r of rows) {
      const amt = Number(r.amount);
      total += amt;
      const cat = catById.get(r.category_id) || 'Uncategorised';
      byCategory.set(cat, (byCategory.get(cat) || 0) + amt);
      const m = String(r.incurred_on).slice(0, 7);
      byMonth.set(m, (byMonth.get(m) || 0) + amt);
    }

    out.spending = {
      total,
      total_formatted: formatAmount(total, currency),
      entry_count: rows.length,
      by_category: [...byCategory.entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([name, amount]) => ({ name, amount, formatted: formatAmount(amount, currency) })),
      by_month: [...byMonth.entries()]
        .sort((a, b) => (a[0] < b[0] ? 1 : -1))
        .slice(0, 12)
        .map(([m, amount]) => ({ month: m, amount, formatted: formatAmount(amount, currency) })),
    };

    if (kind === 'budget' || kind === 'everything') {
      const targetMonth = month || new Date().toISOString().slice(0, 7);
      const { data: budget } = await supabase
        .from('budgets')
        .select('monthly_limit')
        .eq('user_id', userId)
        .eq('month_year', targetMonth)
        .maybeSingle();

      const spentThisMonth = month
        ? total
        : rows
            .filter((r) => String(r.incurred_on).slice(0, 7) === targetMonth)
            .reduce((s, r) => s + Number(r.amount), 0);

      const limit = budget ? Number(budget.monthly_limit) : null;
      out.budget = {
        month: targetMonth,
        limit,
        limit_formatted: limit == null ? null : formatAmount(limit, currency),
        spent: spentThisMonth,
        spent_formatted: formatAmount(spentThisMonth, currency),
        remaining: limit == null ? null : limit - spentThisMonth,
        remaining_formatted: limit == null ? null : formatAmount(limit - spentThisMonth, currency),
        set: limit != null,
      };
    }
  }

  return out;
}

function monthRange(month) {
  const [y, m] = month.split('-').map(Number);
  const start = `${month}-01`;
  const endDate = new Date(Date.UTC(y, m, 0)); // day 0 of next month = last day of this one
  return { start, end: endDate.toISOString().slice(0, 10) };
}

// Everything the user can change about their account, so the model can answer
// "what's my currency / budget / are reminders on" and show a before value.
export async function getSettings(userId) {
  const month = new Date().toISOString().slice(0, 7);
  const [{ data: profile }, { data: reminders }, { data: budget }, cats] = await Promise.all([
    supabase.from('profiles').select('full_name, currency, upi_id').eq('id', userId).maybeSingle(),
    supabase
      .from('reminder_settings')
      .select('reminders_on, reminder_frequency, channel_email, channel_sms, channel_whatsapp, email_subject, email_message, email_closing')
      .eq('user_id', userId)
      .maybeSingle(),
    supabase.from('budgets').select('month_year, monthly_limit').eq('user_id', userId).eq('month_year', month).maybeSingle(),
    listCategories(userId),
  ]);

  return {
    profile: {
      full_name: profile?.full_name || null,
      currency: profile?.currency || 'INR',
      upi_id: profile?.upi_id || null,
    },
    reminders: reminders || { reminders_on: true, reminder_frequency: 'monthly' },
    budget_this_month: budget
      ? { month: budget.month_year, limit: Number(budget.monthly_limit) }
      : { month, limit: null },
    categories: cats.categories,
  };
}

// ── direct create (no confirmation: nothing is overwritten) ────────────

export async function createPerson(userId, { name, description, email, phone, whatsapp } = {}) {
  if (!name || !String(name).trim()) throw badRequest('A name is required to add a contact.');
  const clean = String(name).trim();

  const existing = await resolvePerson(userId, clean);
  if (existing.found && norm(existing.person.name) === norm(clean)) {
    return { created: false, id: existing.person.id, name: existing.person.name, message: `"${existing.person.name}" already exists.` };
  }

  const { data, error } = await supabase
    .from('people')
    .insert({
      user_id: userId,
      name: clean,
      description: description || null,
      email: email || null,
      phone: phone || null,
      whatsapp: whatsapp || null,
    })
    .select('id, name')
    .single();
  if (error) throw new Error(`Could not add "${clean}": ${error.message}`);
  return { created: true, id: data.id, name: data.name };
}

export async function createCategory(userId, { name, icon, color } = {}) {
  if (!name || !String(name).trim()) throw badRequest('A category name is required.');
  const clean = String(name).trim();
  if (color && !/^#[0-9a-fA-F]{6}$/.test(color)) {
    throw badRequest('Colour must be a 6-digit hex code like #6366f1.');
  }

  const existing = await resolveCategory(userId, clean);
  if (existing && norm(existing.name) === norm(clean)) {
    return { created: false, id: existing.id, name: existing.name, message: `Category "${existing.name}" already exists.` };
  }

  const { data, error } = await supabase
    .from('expense_categories')
    .insert({ user_id: userId, name: clean, icon: icon || 'category', color: color || '#6366f1' })
    .select('id, name')
    .single();
  if (error) throw new Error(`Could not create the category: ${error.message}`);
  return { created: true, id: data.id, name: data.name };
}

// ── mutations: preview then apply ──────────────────────────────────────

const MUTATION_KINDS = [
  'update_person',
  'delete_person',
  'update_expense',
  'delete_expense',
  'update_settings',
  'update_category',
  'delete_category',
  'send_reminder',
];

const PERSON_FIELDS = ['name', 'description', 'email', 'phone', 'whatsapp', 'reminders_on'];
const FRIEND_EXPENSE_FIELDS = ['amount', 'note', 'date'];
const PERSONAL_EXPENSE_FIELDS = ['amount', 'note', 'date', 'category', 'payment_mode'];
const SETTINGS_FIELDS = [
  'currency',
  'upi_id',
  'full_name',
  'reminders_on',
  'reminder_frequency',
  'channel_email',
  'channel_sms',
  'channel_whatsapp',
  'email_subject',
  'email_message',
  'email_closing',
  'monthly_budget',
  'budget_month',
];

const PROFILE_KEYS = ['currency', 'upi_id', 'full_name'];
const REMINDER_KEYS = [
  'reminders_on',
  'reminder_frequency',
  'channel_email',
  'channel_sms',
  'channel_whatsapp',
  'email_subject',
  'email_message',
  'email_closing',
];

function pick(changes, allowed) {
  const out = {};
  for (const k of allowed) {
    if (changes && changes[k] !== undefined && changes[k] !== null && changes[k] !== '') out[k] = changes[k];
  }
  return out;
}

// Loads the row a mutation targets, enforcing ownership. Returns null when the
// id is unknown OR belongs to somebody else — the model cannot tell them apart,
// which is the point.
async function loadTarget(userId, action) {
  if (action.kind === 'update_person' || action.kind === 'delete_person') {
    const { data } = await supabase
      .from('people')
      .select('id, name, description, email, phone, whatsapp, reminders_on')
      .eq('user_id', userId)
      .eq('id', action.id)
      .maybeSingle();
    return data || null;
  }
  if (action.kind === 'update_category' || action.kind === 'delete_category') {
    // Only the user's own categories are editable — system presets are shared.
    const { data } = await supabase
      .from('expense_categories')
      .select('id, name, icon, color, is_system')
      .eq('user_id', userId)
      .eq('id', action.id)
      .maybeSingle();
    return data || null;
  }
  if (action.kind === 'send_reminder') {
    const { data } = await supabase
      .from('people')
      .select('id, name, email, phone, whatsapp, reminders_on')
      .eq('user_id', userId)
      .eq('id', action.id)
      .maybeSingle();
    return data || null;
  }
  if (action.kind === 'update_expense' || action.kind === 'delete_expense') {
    const table = action.scope === 'personal' ? 'personal_expenses' : 'expenses';
    const columns =
      action.scope === 'personal'
        ? 'id, amount, note, payment_mode, incurred_on, category_id'
        : 'id, person_id, amount, note, incurred_on';
    const { data } = await supabase
      .from(table)
      .select(columns)
      .eq('user_id', userId)
      .eq('id', action.id)
      .maybeSingle();
    return data || null;
  }
  return null;
}

// Validates an action and renders what it would do. Never writes.
// Returns { previewHtml, action } — the action is re-validated on apply.
export async function previewMutation(userId, rawAction) {
  const action = { ...rawAction };
  if (!MUTATION_KINDS.includes(action.kind)) {
    throw badRequest(`Unknown change type "${action.kind}".`);
  }
  const { currency } = await getUserContext(userId);

  // ── settings ──
  if (action.kind === 'update_settings') {
    const changes = pick(action.changes, SETTINGS_FIELDS);
    if (!Object.keys(changes).length) throw badRequest('No settings to change.');
    if (changes.currency && !/^[A-Za-z]{3}$/.test(changes.currency)) {
      throw badRequest('Currency must be a 3-letter code like INR or USD.');
    }
    if (changes.currency) changes.currency = changes.currency.toUpperCase();
    if (changes.reminder_frequency && !['weekly', 'monthly'].includes(changes.reminder_frequency)) {
      throw badRequest('Reminder frequency must be weekly or monthly.');
    }
    if (changes.monthly_budget != null) {
      const n = Number(changes.monthly_budget);
      if (!Number.isFinite(n) || n <= 0) throw badRequest('The budget must be a positive number.');
      changes.monthly_budget = n;
      changes.budget_month = changes.budget_month || new Date().toISOString().slice(0, 7);
      if (!isMonth(changes.budget_month)) throw badRequest('budget_month must be YYYY-MM.');
    }

    const lines = Object.entries(changes)
      .filter(([k]) => k !== 'budget_month')
      .map(([k, v]) => {
        if (k === 'monthly_budget') {
          return `• Budget for <b>${esc(changes.budget_month)}</b> → ${esc(formatAmount(v, changes.currency || currency))}`;
        }
        return `• ${esc(k.replaceAll('_', ' '))} → <b>${esc(String(v))}</b>`;
      });
    return {
      action: { ...action, changes },
      previewHtml: `⚙️ Update settings:\n\n${lines.join('\n')}`,
    };
  }

  // ── everything else targets a row ──
  const target = await loadTarget(userId, action);
  if (!target) {
    throw badRequest("I couldn't find that record — it may already be gone. Try listing it again.");
  }

  if (action.kind === 'update_person') {
    const changes = pick(action.changes, PERSON_FIELDS);
    if (!Object.keys(changes).length) throw badRequest('No contact details to change.');
    if (changes.name) {
      const clean = String(changes.name).trim();
      if (!clean) throw badRequest('The new name cannot be empty.');
      const clash = await supabase
        .from('people').select('id, name').eq('user_id', userId).neq('id', target.id);
      const dupe = (clash.data || []).find((p) => norm(p.name) === norm(clean));
      if (dupe) throw badRequest(`You already have a contact called "${dupe.name}".`);
      changes.name = clean;
    }
    const lines = Object.entries(changes).map(
      ([k, v]) => `• ${esc(k.replaceAll('_', ' '))}: ${esc(String(target[k] ?? '—'))} → <b>${esc(String(v))}</b>`,
    );
    return {
      action: { ...action, changes },
      previewHtml: `✏️ Update <b>${esc(target.name)}</b>:\n\n${lines.join('\n')}`,
    };
  }

  if (action.kind === 'delete_person') {
    const { count } = await supabase
      .from('expenses')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', userId)
      .eq('person_id', target.id);
    const { data: bal } = await supabase
      .from('person_balances').select('balance').eq('person_id', target.id).maybeSingle();
    const entries = count ?? 0;
    return {
      action,
      previewHtml:
        `🗑 Delete contact <b>${esc(target.name)}</b>?\n\n` +
        `This also deletes their <b>${entries}</b> ledger ${entries === 1 ? 'entry' : 'entries'} ` +
        `and the balance of ${esc(formatAmount(Number(bal?.balance ?? 0), currency))}.\n` +
        `<i>This cannot be undone.</i>`,
    };
  }

  if (action.kind === 'update_category') {
    const changes = pick(action.changes, ['name', 'icon', 'color']);
    if (!Object.keys(changes).length) throw badRequest('No category details to change.');
    if (changes.color && !/^#[0-9a-fA-F]{6}$/.test(changes.color)) {
      throw badRequest('Colour must be a 6-digit hex code like #6366f1.');
    }
    if (changes.name) {
      const clean = String(changes.name).trim();
      if (!clean) throw badRequest('The category name cannot be empty.');
      const existing = await resolveCategory(userId, clean);
      if (existing && existing.id !== target.id && norm(existing.name) === norm(clean)) {
        throw badRequest(`A category called "${existing.name}" already exists.`);
      }
      changes.name = clean;
    }
    const lines = Object.entries(changes).map(
      ([k, v]) => `• ${esc(k)}: ${esc(String(target[k] ?? '—'))} → <b>${esc(String(v))}</b>`,
    );
    return {
      action: { ...action, changes },
      previewHtml: `✏️ Update category <b>${esc(target.name)}</b>:\n\n${lines.join('\n')}`,
    };
  }

  if (action.kind === 'delete_category') {
    const { count } = await supabase
      .from('personal_expenses')
      .select('id', { count: 'exact', head: true })
      .eq('user_id', userId)
      .eq('category_id', target.id);
    const n = count ?? 0;
    return {
      action,
      previewHtml:
        `🗑 Delete category <b>${esc(target.name)}</b>?\n\n` +
        (n
          ? `${n} ${n === 1 ? 'expense keeps' : 'expenses keep'} their amount but become uncategorised.`
          : 'No expenses use it.'),
    };
  }

  if (action.kind === 'send_reminder') {
    const { data: bal } = await supabase
      .from('person_balances').select('balance').eq('person_id', target.id).maybeSingle();
    const owed = Number(bal?.balance ?? 0);
    if (owed <= 0) throw badRequest(`${target.name} doesn't owe anything right now, so there's nothing to remind about.`);
    const channels = [
      target.email && 'email',
      target.phone && 'SMS',
      target.whatsapp && 'WhatsApp',
    ].filter(Boolean);
    if (!channels.length) {
      throw badRequest(`${target.name} has no email, phone or WhatsApp saved, so I can't send a reminder. Add a contact detail first.`);
    }
    return {
      action,
      previewHtml:
        `📣 Send a payment reminder to <b>${esc(target.name)}</b> for ${esc(formatAmount(owed, currency))}?\n\n` +
        `Via: ${esc(channels.join(', '))}\n<i>This contacts them directly.</i>`,
    };
  }

  const scope = action.scope === 'personal' ? 'personal' : 'friend';
  const label = await describeExpense(userId, scope, target, currency);

  if (action.kind === 'delete_expense') {
    return {
      action: { ...action, scope },
      previewHtml: `🗑 Delete this ${scope === 'personal' ? 'personal expense' : 'ledger entry'}?\n\n${label}\n\n<i>This cannot be undone.</i>`,
    };
  }

  // update_expense
  const allowed = scope === 'personal' ? PERSONAL_EXPENSE_FIELDS : FRIEND_EXPENSE_FIELDS;
  const changes = pick(action.changes, allowed);
  if (!Object.keys(changes).length) {
    throw badRequest(`Nothing to change. For a ${scope} expense you can set: ${allowed.join(', ')}.`);
  }
  if (changes.amount != null) {
    const n = Number(changes.amount);
    if (!Number.isFinite(n)) throw badRequest('The amount must be a number.');
    if (scope === 'personal' && n <= 0) throw badRequest('A personal expense amount must be positive.');
    if (scope === 'friend' && n === 0) throw badRequest('A ledger amount cannot be zero.');
    changes.amount = n;
  }
  if (changes.date != null && !isDate(changes.date)) throw badRequest('The date must be YYYY-MM-DD.');
  if (changes.payment_mode != null && !PAYMENT_MODES.includes(changes.payment_mode)) {
    throw badRequest(`Payment mode must be one of: ${PAYMENT_MODES.join(', ')}.`);
  }
  if (changes.category != null) {
    const cat = await resolveCategory(userId, changes.category);
    if (!cat) {
      const { categories } = await listCategories(userId);
      throw badRequest(`No category matching "${changes.category}". Available: ${categories.map((c) => c.name).join(', ')}.`);
    }
    changes.category = cat.name;
    changes.category_id = cat.id;
  }

  const lines = Object.entries(changes)
    .filter(([k]) => k !== 'category_id')
    .map(([k, v]) => {
      const before =
        k === 'amount' ? formatAmount(Number(target.amount), currency)
        : k === 'date' ? target.incurred_on
        : k === 'note' ? (target.note || '—')
        : k === 'payment_mode' ? target.payment_mode
        : '—';
      const after = k === 'amount' ? formatAmount(Number(v), currency) : String(v);
      return `• ${esc(k)}: ${esc(String(before))} → <b>${esc(after)}</b>`;
    });

  return {
    action: { ...action, scope, changes },
    previewHtml: `✏️ Update this ${scope === 'personal' ? 'personal expense' : 'ledger entry'}:\n\n${label}\n\n${lines.join('\n')}`,
  };
}

async function describeExpense(userId, scope, row, currency) {
  if (scope === 'personal') {
    const { categories } = await listCategories(userId);
    const cat = categories.find((c) => c.id === row.category_id)?.name || 'Uncategorised';
    return `<b>${esc(formatAmount(Number(row.amount), currency))}</b> — ${esc(row.note || 'no note')} (${esc(cat)}, ${esc(row.incurred_on)})`;
  }
  const { data: person } = await supabase
    .from('people').select('name').eq('id', row.person_id).maybeSingle();
  return `<b>${esc(person?.name || 'Unknown')}</b>  ${esc(formatAmount(Number(row.amount), currency))} — ${esc(row.note || 'no note')} (${esc(row.incurred_on)})`;
}

// Performs a previously previewed mutation. Re-checks ownership rather than
// trusting the stashed payload: the row may have been deleted in between, and
// the pending record round-trips through the database.
export async function applyMutation(userId, action) {
  if (!MUTATION_KINDS.includes(action?.kind)) throw badRequest('Unknown change type.');

  if (action.kind === 'update_settings') {
    const c = action.changes || {};
    const profile = pick(c, PROFILE_KEYS);
    const reminders = pick(c, REMINDER_KEYS);
    const done = [];

    if (Object.keys(profile).length) {
      const { error } = await supabase.from('profiles').update(profile).eq('id', userId);
      if (error) throw new Error(`Could not update your profile: ${error.message}`);
      done.push(Object.keys(profile).join(', '));
    }
    if (Object.keys(reminders).length) {
      const { error } = await supabase
        .from('reminder_settings')
        .upsert({ user_id: userId, ...reminders }, { onConflict: 'user_id' });
      if (error) throw new Error(`Could not update reminder settings: ${error.message}`);
      done.push(Object.keys(reminders).join(', '));
    }
    if (c.monthly_budget != null) {
      const { error } = await supabase
        .from('budgets')
        .upsert(
          { user_id: userId, month_year: c.budget_month, monthly_limit: c.monthly_budget },
          { onConflict: 'user_id,month_year' },
        );
      if (error) throw new Error(`Could not set the budget: ${error.message}`);
      done.push(`budget for ${c.budget_month}`);
    }
    return { ok: true, message: `✅ Updated ${done.join(' and ')}.` };
  }

  const target = await loadTarget(userId, action);
  if (!target) throw badRequest("That record no longer exists — nothing was changed.");

  if (action.kind === 'update_person') {
    const { error } = await supabase
      .from('people')
      .update({ ...action.changes, updated_at: new Date().toISOString() })
      .eq('user_id', userId)
      .eq('id', target.id);
    if (error) throw new Error(`Could not update the contact: ${error.message}`);
    return { ok: true, message: `✅ Updated <b>${esc(action.changes.name || target.name)}</b>.` };
  }

  if (action.kind === 'delete_person') {
    // expenses.person_id cascades, so the ledger rows go with the contact.
    const { error } = await supabase
      .from('people').delete().eq('user_id', userId).eq('id', target.id);
    if (error) throw new Error(`Could not delete the contact: ${error.message}`);
    return { ok: true, message: `✅ Deleted <b>${esc(target.name)}</b> and their entries.` };
  }

  if (action.kind === 'update_category') {
    const { error } = await supabase
      .from('expense_categories')
      .update(action.changes)
      .eq('user_id', userId)
      .eq('id', target.id);
    if (error) throw new Error(`Could not update the category: ${error.message}`);
    return { ok: true, message: `✅ Category updated to <b>${esc(action.changes.name || target.name)}</b>.` };
  }

  if (action.kind === 'delete_category') {
    // personal_expenses.category_id is ON DELETE SET NULL, so the expenses
    // survive as uncategorised rather than disappearing with the category.
    const { error } = await supabase
      .from('expense_categories').delete().eq('user_id', userId).eq('id', target.id);
    if (error) throw new Error(`Could not delete the category: ${error.message}`);
    return { ok: true, message: `✅ Deleted category <b>${esc(target.name)}</b>.` };
  }

  if (action.kind === 'send_reminder') {
    const summary = await remindPerson(target.id, userId);
    const sent = summary?.sent ?? 0;
    if (!sent) {
      return { ok: true, message: `⚠️ Nothing was sent to <b>${esc(target.name)}</b> — check the reminder channels in Settings.` };
    }
    return { ok: true, message: `✅ Reminder sent to <b>${esc(target.name)}</b> (${sent} ${sent === 1 ? 'message' : 'messages'}).` };
  }

  const scope = action.scope === 'personal' ? 'personal' : 'friend';
  const table = scope === 'personal' ? 'personal_expenses' : 'expenses';

  if (action.kind === 'delete_expense') {
    const { error } = await supabase
      .from(table).delete().eq('user_id', userId).eq('id', target.id);
    if (error) throw new Error(`Could not delete the entry: ${error.message}`);
    return { ok: true, message: '✅ Entry deleted.' };
  }

  const c = action.changes || {};
  const patch = { updated_at: new Date().toISOString() };
  if (c.amount != null) patch.amount = c.amount;
  if (c.note != null) patch.note = c.note;
  if (c.date != null) patch.incurred_on = c.date;
  if (scope === 'personal') {
    if (c.payment_mode != null) patch.payment_mode = c.payment_mode;
    if (c.category_id != null) patch.category_id = c.category_id;
  }

  const { error } = await supabase
    .from(table).update(patch).eq('user_id', userId).eq('id', target.id);
  if (error) throw new Error(`Could not update the entry: ${error.message}`);

  // Report the resulting balance for friend entries — that's what the user
  // actually cares about after editing one.
  if (scope === 'friend') {
    const { currency } = await getUserContext(userId);
    const { data: bal } = await supabase
      .from('person_balances').select('balance').eq('person_id', target.person_id).maybeSingle();
    const { data: person } = await supabase
      .from('people').select('name').eq('id', target.person_id).maybeSingle();
    return {
      ok: true,
      message: `✅ Entry updated. <b>${esc(person?.name || 'They')}</b> now owes ${esc(formatAmount(Number(bal?.balance ?? 0), currency))}.`,
    };
  }
  return { ok: true, message: '✅ Expense updated.' };
}

export { esc as escapeHtml };
